// <auto-generated />
namespace CarRentalMVC_ASP.NET.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddRentalsTabel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddRentalsTabel));
        
        string IMigrationMetadata.Id
        {
            get { return "202505221902355_AddRentalsTabel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
